### ISSUE TITLE
Translation: R-gapminder "Introduction"

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#105]
Translation: R-gapminder "Introduction" (index.md and README.md)
-----

http://swcarpentry.github.io/r-novice-gapminder/

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/f4aed5e805895a613b0cdffffefd0431a75ac54d/po/r-novice-gapminder.ja.po#L709-L736

The section below has already been translated, but should be reviewed:
以下のところは翻訳済みですが、まだレビューが必要です：

https://github.com/swcarpentry-ja/i18n/blob/71daf97d7335f914d216d9caff175ff0037fbd09/po/r-novice-gapminder.ja.po#L21130-L21163

**Comment by TomKellyGenetics** [comment]
Those sections were me when I first set up the repo: https://github.com/swcarpentry-ja/i18n/blame/d85e3401489828df44ed7a6c3a5e10dd24761957/po/r-novice-gapminder.ja.po#L21156-L21176

So they'll definitely need to be double-checked :-)

**Comment by masamiy** [comment]
I am happy to take part.
