### ISSUE TITLE
Migrate changes to  other lessons

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#11]
There are a number of files shared between lessons as part of the Software Carpentry lesson template:

```
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.md
README.md
aio.md
index.md
reference.md
setup.md
```

These are internal files in the lesson github repo and are not displayed on the rendered webpage. They can only be found on the lesson repo and are intended as a guide to using (and contributing to the repo itself). These are not specific to each lesson and could be copied between them. They are currently being translated #10 for the git lesson. Please refer to these files and transfer translations for these files when working on a new lesson.

Not only does this save repeating each other, it will be best to be consistent across lessons (as the English text is). However, the English version assumes that contributions can be made directly to the lesson repo. If the translation is a mirror of the current English lesson, we should instead instruct users to send a PR to the English lesson to request changes (if they can in English) or raise an issue in the local language to suggest a change to the English and localised lessons. #12

**Comment by TomKellyGenetics** [comment]
Translators working on other lessons have been instructed to skip the following files. These should be copied to be consistent with the Git lesson.

```
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.md
```

**Comment by dpshelio** [comment]
This is something we should be able to automate (if all are exactly the same)

**Comment by TomKellyGenetics** [comment]
We've taken care of this with #131 and #136 for now. I think automation is a good idea though!

**Comment by TomKellyGenetics** [comment]
Also note that I was wrong. These files are included in the PO files., for example:

```
 $ grep "git-novice" git-novice.ja.po | grep "md" | cut -d":" -f2 | sort | uniq
 git-novice/CODE_OF_CONDUCT.md
 git-novice/CONTRIBUTING.md
 git-novice/LICENSE.md
 git-novice/README.md
 git-novice/_episodes/01-basics.md
 git-novice/_episodes/02-setup.md
 git-novice/_episodes/03-create.md
 git-novice/_episodes/04-changes.md
 git-novice/_episodes/05-history.md
 git-novice/_episodes/06-ignore.md
 git-novice/_episodes/07-github.md
 git-novice/_episodes/08-collab.md
 git-novice/_episodes/09-conflict.md
 git-novice/_episodes/10-open.md
 git-novice/_episodes/11-licensing.md
 git-novice/_episodes/12-citation.md
 git-novice/_episodes/13-hosting.md
 git-novice/_episodes/14-supplemental-rstudio.md
 git-novice/_extras/about.md
 git-novice/_extras/discuss.md
 git-novice/_extras/figures.md
 git-novice/_extras/guide.md
 git-novice/aio.md
 git-novice/index.md
 git-novice/reference.md
 git-novice/setup.md
```

**Comment by joelnitta** [comment]
Thanks for the clarification Tom!
