### ISSUE TITLE
Problems with R-novice-gapminder table of contents and headers

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#116]
There are several small things that need to be fixed in the latest rendered [R-novice-gapminder translation](https://swcarpentry-ja.github.io/r-novice-gapminder/ja/index/index.html).

In the table of contents:
- Lesson 5 title is in English
- Lesson 8 is empty
- Lesson 13 title is in in English
- The translation for "finish" as 仕上がり doesn't really make sense in this context (consider changing in [lang.md](https://github.com/swcarpentry-ja/i18n/blob/ja/lang.md)). Probably 終わり is better?

In the outline for each lesson, "Teaching" still shows up as　教えります (should be 講義, as set in `lang.md`)

**Comment by TomKellyGenetics** [comment]
Looks like the following lines weren't translated in PR #114.

https://github.com/swcarpentry-ja/i18n/blob/e8e5ac3fac015064959ef95db832756f93e02370/po/r-novice-gapminder.ja.po#L7111

https://github.com/swcarpentry-ja/i18n/blob/e8e5ac3fac015064959ef95db832756f93e02370/po/r-novice-gapminder.ja.po#L16820

I'll handle the technical side, suggestions welcome but if I've badly translated, we can always handle in when checking the PR.

Seems to be an issue here too.

https://github.com/swcarpentry-ja/i18n/blob/e8e5ac3fac015064959ef95db832756f93e02370/po/r-novice-gapminder.ja.po#L12297

I'll ry building a corrected lesson on my user account (https://tomkellygenetics.github.io/r-novice-gapminder/ja/index/index.html) before updating the files here.

**Comment by TomKellyGenetics** [comment]
Translating this consistent with the introduction to the lesson and name of the following lesson.

> Lesson 13: dplyrによるデータフレームの操作
> Lesson 14: tidyによるデータフレームの操作

**Comment by TomKellyGenetics** [comment]
This seems to be a problem with wrapper script. I'll look into it further.

Lesson 8 and the TOCs are corrected now. The issue with lesson 8 was `"keypoints:"` field in template translated.  I'll submit changes to PO files to do this on `i18n` as a PR. Remotes `r-novice-gapminder` and `r-novice-gapminder-ja` are updated already (major changes here: https://github.com/swcarpentry-ja/r-novice-gapminder-ja/commit/7b65cdff75d5f7ccdd518313aaea468b6f933686).
https://swcarpentry-ja.github.io/r-novice-gapminder/ja/_episodes/08-plot-ggplot2/index.html

There seems to be an issue updating `lang.md`. Troubleshooting this is not trivial and will need more time. I think titles are correct now though.

> キーポイント -> まとめ
> 仕上がり -> 終わり
> 教えります ->  講義

**Comment by TomKellyGenetics** [comment]
Was meaning to submit as a PR but changes have been pushed to the organisation repo: https://github.com/swcarpentry-ja/i18n/commit/ad61e94761935ea8a1429fbdc0eb53438b370e8e

**Comment by TomKellyGenetics** [comment]
Sorry merged #117 via command-line. Please check these translations. 

Lesson 5:

https://github.com/swcarpentry-ja/i18n/blob/b9e389162b434400dc1ba7375c03edba8cb46503/po/r-novice-gapminder.ja.po#L7111

Lesson 8:

Translated by @asusy (formatting corrected).

Lesson 13:

https://github.com/swcarpentry-ja/i18n/blob/b9e389162b434400dc1ba7375c03edba8cb46503/po/r-novice-gapminder.ja.po#L16820
