### ISSUE TITLE
 Translation: R-gapminder "Code of Conduct" (CODE_OF_CONDUCT.md)

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#122]
Original webpage: http://swcarpentry.github.io/r-novice-gapminder/CODE_OF_CONDUCT.html

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/1decdaf5e19184459fa26ca57d9cf9ecd7466eb5/po/r-novice-gapminder.ja.po#L20-L62

**Comment by TomKellyGenetics** [comment]
Thinking we could do a similar thing to the License #127 by pulling existing translations of excerpts. I guess it depends if we:

1.  translate the text in the [current](https://github.com/swcarpentry/shell-novice/blob/gh-pages/CODE_OF_CONDUCT.md) "Code of Conduct" page which links to the [full code of conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) in English
2. translate the [previous version](https://swcarpentry-ja.github.io/shell-novice/conduct/) which had a longer explanation of the Code of Conduct
3. translate the full Code of Conduct

Short version (1)

```
---
layout: page
title: "Contributor Code of Conduct"
---
As contributors and maintainers of this project,
we pledge to follow the [Carpentry Code of Conduct][coc].

Instances of abusive, harassing, or otherwise unacceptable behavior
may be reported by following our [reporting guidelines][coc-reporting].

{% include links.md %}
```

Long version (2)

```
---
layout: page
title: "Contributor Code of Conduct"
permalink: /conduct/
---
As contributors and maintainers of this project,
we pledge to respect all people who contribute through reporting issues,
posting feature requests,
updating documentation,
submitting pull requests or patches,
and other activities.

We are committed to making participation in this project a harassment-free experience for everyone,
regardless of level of experience,
gender,
gender identity and expression,
sexual orientation,
disability,
personal appearance,
body size,
race,
ethnicity,
age,
or religion.

Examples of unacceptable behavior by participants include the use of sexual language or imagery,
derogatory comments or personal attacks,
trolling,
public or private harassment,
insults,
or other unprofessional conduct.

Project maintainers have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to our [Code of Conduct][coc].
Project maintainers who do not follow the Code of Conduct may be removed from the project team.

Instances of abusive, harassing, or otherwise unacceptable behavior
may be reported by following our [reporting guidelines][coc-reporting].


- [Software and Data Carpentry Code of Conduct][coc]
- [Code of Conduct Reporting Guide][coc-reporting]

{% include links.md %}
```

Option (3) seems ambitious but has the advantage of being unambiguous to Japanese participants in workshops (in case they do not understand English well). The [Django project](https://www.djangoproject.com/start/overview/) explains their code of conduction [here](https://github.com/django/code-of-conduct). This was used as the basis for the [ADA Initiative template](https://geekfeminism.wikia.org/wiki/Conference_anti-harassment/Policy#Anti-harassment_policy_text) that The Carpentries used.

I've found a few examples of this template translated into Japanese that may be useful if we decide to do that:

http://opensource.guide/ja/code-of-conduct/

https://www.linuxfoundation.jp/code-of-conduct/

https://hackmd.io/@codeforjapan/hackday/https%3A%2F%2Fhackmd.io%2Fs%2FSJogO4pYM?type=book

**Comment by fmichonneau** [comment]
the short version (1) is the official one for repositories. The long version (2) is out of date.

**Comment by joelnitta** [comment]
I think we should go with (1), since that has the advantages of being both short and official.

I think for now we should consider content in the Handbook out of the scope of the translation project. I could see eventually making exceptions for very important material, such as the Code of Conduct. Then the only question is where to put it...

**Comment by TomKellyGenetics** [comment]
Thanks for weighing in on this @fmichonneau. That is helpful.

It is actually easier for us to translate the short version. Unfortunately this will link to the full version in English for now.

I hear there are efforts to translate the Handbook as well but let's leave that for now.

**Comment by TomKellyGenetics** [comment]
There is a dedicated repository for translating the Handbook here: https://github.com/carpentries-i18n/handbook-translations
