### ISSUE TITLE
Translation: R-gapminder "Setup" (setup.md)

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#125]
Translation: R-gapminder "Setup" (setup.md)
-----

Original webpage: http://swcarpentry.github.io/r-novice-gapminder/setup.html

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/1decdaf5e19184459fa26ca57d9cf9ecd7466eb5/po/r-novice-gapminder.ja.po#L22183-L22214

**Comment by kozo2** [comment]
@joelnitta Please assign this to me

**Comment by TomKellyGenetics** [comment]
Currently lines: https://github.com/swcarpentry-ja/i18n/blob/ja/po/r-novice-gapminder.ja.po#L22210-L22241

https://github.com/swcarpentry-ja/i18n/blob/e8631376bf4ef98b44a5f151af40f143dcdc2a04/po/r-novice-gapminder.ja.po#L22210-L22241
