### ISSUE TITLE
Guidelines for Translators

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#13]
The Spanish team has clear guidelines for translators to ensure consistent style across different lesson and contributors. They have a dedicated repo for theirs:

https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md

I think ours could be included here since we are using a newer system. Many of these are specific to the Spanish language (such as gender, plurals, or pronouns) so are not such an issue with Japanese. Still matters such as the level of formality #10 should be agreed on (and made clear for non-native speakers who may not understand conventions of when to use formal language).

I've set up a `CultureNotes.md` for non-literal translations and cultural considerations but perhaps we need basic guidelines on language style as well. The Spanish version has also been used for translating R and data science books. If anyone has experience with book translations between English and Japanese, we could use similar style to those projects.

**Comment by TomKellyGenetics** [comment]
Guidelines for TED will be used (as suggested by @kyyonko). These may be adapted for the purposes of Software Carpentry.

https://translations.ted.com/TED_%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%AD%97%E5%B9%95%E3%81%AE%E8%A1%A8%E8%A8%98%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3

**Comment by dpshelio** [comment]
How come I had forgotten about the TED community!!! Thanks for finding it!! :)
