### ISSUE TITLE
Translation: Library Carpentry OpenRefine "Setup"

### ISSUE THREAD

**Issue by kozo2** [swcarpentry-ja/i18n#151]

**Comment by kozo2** [comment]
I translated this here #154

**Comment by masamiy** [comment]
Thanks @kozo2 , I will have a look.

**Comment by joelnitta** [comment]
Translation: Library Carpentry OpenRefine "Setup"
-----

Original: https://librarycarpentry.org/lc-open-refine/setup.html

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/bb59a567c061b1ac798065838a9cd85b518b90d2/po/lc-open-refine.ja.po#L2646-L2794
