### ISSUE TITLE
About using translation tool like Google Translator

### ISSUE THREAD

**Issue by manabuishii** [swcarpentry-ja/i18n#19]
There are a lot of tool good for translation.
But sometimes tools license is conflict against document license.

Sorry I don't know much about Software Carpentry Document license.

How do you think about using Google Translator or other tools ?

I thinks at least
 if contributors are using some tools including web tool,
　they inform tool name .
 
1 example:
- [Ubuntu Case](https://wiki.ubuntulinux.jp/IRCMeeting/20170304)

**Comment by TomKellyGenetics** [comment]
I would prefer if we did not need to use these tools (although I will confess to using them myself for the demo). These tools are not perfect and the cultural background of Japanese learners must be considered. That is why we are getting native Japanese speakers (with strong English skills) to assist with the translations. Once we have translated versions of the lessons, English should not be needed to improve them and anyone able to read Japanese is welcome to assist at that stage.

I think foreigners (such as myself) with intermediate level Japanese can also contribute. This will be easier once we have a team checking each others lessons as at the moment, I'm wary to make too many mistakes. We have several people with native-level English who have been involved in teaching Software Carpentry before who can assist if anything is unclear and difficult to understand in the English version.

I'm aware that this is a difficult topic in a foreign language (which is part of the motivation for making localised lessons in Japanese).

Another tool that I use for technical terms: https://jisho.org/about

At the moment, I think it's most important to acknowledge the contributions of those involved. I'd rather not use automated translation tools unless we need to. If we do, will need to make sure it is acceptable for opensource/non-profit use.
