### ISSUE TITLE
Consistent way to translate English abbreviations and commands

### ISSUE THREAD

**Issue by rikutakei** [swcarpentry-ja/i18n#21]
This does raise an issue that could come up again. Terminology like "REPL" is obvious (self-explanatory) for English-speakers but needs more explanation in a foreign language. Is it better to keep the full English term and explain the meaning of each word?

> REPL (read-evaluate-print-loop)と呼ばれています。
>  英語で読み込みはreadです。英語で評価はevaluateです。英語で出力はprintです。英語でループはloopです。

I know this might seem tedious but maybe notes like this to explain English terminology may be needed (similarly for concepts like "ls" for "list").

_Originally posted by @TomKellyGenetics in https://github.com/swcarpentry-ja/i18n/pull/20#issuecomment-436107171_

**Comment by rikutakei** [comment]
Please read the thread from this [pull request](https://github.com/swcarpentry-ja/i18n/pull/20#issuecomment-436107171) first.

**Comment by manabuishii** [comment]
Thanks comments and creating issue about *REPL*  👍 
I update #20 .

I think explain each word is good for beginers.

**Comment by TomKellyGenetics** [comment]
Thanks for raising the issue. It’s something we needed to discuss and I think we all agree on how to go about it. This has been considered and included in the guidelines.
