### ISSUE TITLE
Standardise the Language-Team tag in the po files

### ISSUE THREAD

**Issue by peterjc** [swcarpentry-ja/i18n#3]
There is currently a mixture:

```
$ grep "Language-Team" *.po
git-novice.es.po:"Language-Team: Spanish <dps.helio@gmail.com>\n"
git-novice.ja.po:"Language-Team: Japanese_Test\n"
git-novice.jp.po:"Language-Team: Japanese_Test\n"
python-novice-gapminder.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
python-novice-inflammation.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
r-novice-gapminder.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
r-novice-inflammation.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
shell-novice.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
sql-novice-survey.ja.po:"Language-Team: LANGUAGE <LL@li.org>\n"
```

Note ``git-novice.es.po`` can be ignored as per #1

**Comment by TomKellyGenetics** [comment]
We haven't yet discussed how the Japanese Team will be contacted. At the moment, these are placeholders to get the demo lesson to compile correctly. These will be updated once that is decided. We will try to be consistent with Spanish where possible.

We are removing JP (Country code: Japan) and switching to JA (Language code: Japanese).
