### ISSUE TITLE
Revisions to R-gapminder (Lesson 6)

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#55]
This is a follow up to merging PR #42.

Sections: 5, 6, 7, 15, and 16 are still being reviewed and edited. Please refer to the respective PR for each or open a new one. We will now review and edit each lesson separately.

Sections 12, 13, and 14 are still being translated (see Issues #52 #53 and #54 respectively).

**Comment by TomKellyGenetics** [comment]
If help is needed with creating separate branches on GitHub, I can handle this an open new PRs.

**Comment by joelnitta** [comment]
There are now individual issues or PRs for translation (#52, #53, #54) and review (#50, #59, #60) for each of these. I am closing this so we don't have to keep track of them in multiple places.
