### ISSUE TITLE
Review: R-gapminder Section 6

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#59]
Translation review: R-gapminder Section 6 "Subsetting Data" (lines 8355 to 11055)
-----

All future reviews will be done for each section when the initial translation is submitted as a PR.
Section 6 has already been translated and merged, but not reviewed, so we are doing this review "after-the-fact".

* Please assign yourself to the issue **before** you start reviewing, so other people know that you are reviewing
* During your review, please edit or add a comment for each line that you think needs correction in this section
* Once you have reviewed the section, send a pull request and reference this issue
* (If nothing needs fixing, please comment as such and close this issue!)

翻訳のレビュー：R-gapminder セクション６ 「Subsetting Data」 (8355 から 11055 まで)
-----

これからの翻訳のレビューは最初に翻訳がPRとして入ってきた時に行う予定ですが、このセクションの翻訳がすでにレビューなしでマージされましたので例外的に「事後」のレビューを行なっています。

* あなたがレビューし始めたと分かるように、レビューを**始める前**にこのイシューを自分に割り振って(assign)して下さい。
* レビューする際、直す必要があると思われるところを一行ずつ添削しあるいはコメントを入れて下さい。
* レビューが終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。
* （もし翻訳はこのまま何も直す必要がないようでしたら、その趣をコメントに書いて、このイシューをク解決（close）して下さい。）

https://github.com/swcarpentry-ja/i18n/blob/ja/po/r-novice-gapminder.ja.po#L8355-L11055

**Comment by rikutakei** [comment]
Been reviewed - see PR #88
