### ISSUE TITLE
Add more detail to the README

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#8]
Add details on how to send a PR for users not familiar with Git.

https://github.com/swcarpentry-i18n/i18n/issues/8

**Comment by rikutakei** [comment]
I think the `quickstart guide` will be a good starting point - If they have any trouble with it, they can post on Slack/TopicBox or open an issue.

Closing this issue

**Comment by TomKellyGenetics** [comment]
Agreed. Now that the README is cluttered enough already and we have a few contributors involved, I think there is enough support to get help if needed.
